version: "3.9"
services:
  frontend:
    container_name: front-paperworksmanager
    image: front-paperworksmanager:1.0.0
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: back-paperworksmanager
    image: back-paperworksmanager:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
